import os
import sys
import json
import requests

# Base endpoint for your specific instance
BASE_URL = "https://ven05174.service-now.com"
API_ENDPOINT = f"{BASE_URL}/api/now/table/incident"

# Read credentials from AAP Custom Credential (or environment variables)
USERNAME = os.getenv("SN_USERNAME", "your_servicenow_user")
PASSWORD = os.getenv("SN_PASSWORD", "your_servicenow_password")

headers = {
    "Content-Type": "application/json",
    "Accept": "application/json"
}

payload = {
    "short_description": os.getenv("INCIDENT_SUMMARY", "Disk Usage Alert Generated by AAP"),
    "description": os.getenv("INCIDENT_DETAIL", "High Disk Usage Report"),
    "urgency": os.getenv("INCIDENT_URGENCY", "3"),
    "impact": os.getenv("INCIDENT_IMPACT", "3"),
    "category": "Hardware",
    "caller_id": "Troy Ellis",
    "state": "1"
}

def create_incident():
    try:
        response = requests.post(
            API_ENDPOINT,
            auth=(USERNAME, PASSWORD),
            headers=headers,
            json=payload,
            timeout=15
        )

        if response.status_code == 201:
            result = response.json().get("result", {})
            output = {
                "success": True,
                "number": result.get("number"),
                "sys_id": result.get("sys_id"),
                "state": result.get("incident_state"),
                "instance": BASE_URL
            }
            print(json.dumps(output, indent=2))
            sys.exit(0)
        else:
            error_data = {
                "success": False,
                "status_code": response.status_code,
                "response": response.text
            }
            print(json.dumps(error_data, indent=2))
            sys.exit(1)

    except requests.exceptions.RequestException as e:
        print(json.dumps({"success": False, "error": str(e)}))
        sys.exit(1)

if __name__ == "__main__":
    create_incident()

