---
- name: Hello World Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5050

  rules:
    - name: Run job restart process
      condition: event.alert.ProblemTitle == "Apache Service Down"
      action:
        run_job_template:
          name: Fix Web
          organization: Default

