---
- name: Listen for Events for Web Application
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: 60
        verify_ssl: false
        urls:
          - http://34.204.68.212
  
  rules:
    - name: Pizza Order Placed
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: Order Placed
          organization: Default 
