---
- name: Listen for Events for Web Application
  hosts: all
  sources:
    - dynatrace.eda.dt_esa_api:
        dt_api_host: https://pjt81419.live.dynatrace.com
        dt_api_token: dt0c01.U6FS5B5V6UTD6NVJ43H43G56.Y4JAJAIPFRTW26L5AV4TOGLKP2MLJ6WCNLB24NVEWCPWLDKVG2KJH5XUNBDTIRMT
        delay: 30
  
  rules:
    - name: Application Failure
      condition: event.payload.problemTitle contains "Apache"
      action:
        run_job_template:
          name: Remediate Application Issue
          organization: Default

    - name: CPU Saturation
      condition: event.payload.problemTitle contains "CPU saturation"
      action:
        run_job_template:
          name: Remediate CPU saturation
          organization: Default 
