---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: all
  sources:
    - name: Listen for Alerts
      ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: EDA AlertManager Run playbook to handle firing alert
      condition: event.alert.status == "firing"
      actions:
        run_job_template:
          name: Fix Web
          organization: Default

    - name: EDA AlertManager Run playbook to handle resolved alert
      condition: event.alert.status == "resolved"
      actions:
        run_job_template:
          name: System Up
          organization: Default
