---
- name: Listen for Events for Web Application
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: 60
        urls:
          - http://3.88.131.86
  
  rules:
    - name: Application is Down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: Fix Cloud Application
          organization: Default 
