---
- name: Listen for Events for Web Application
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: 60
        verify_ssl: false
        urls:
          - http://54.88.87.212
  
  rules:
    - name: HR Portal System is Down
      condition: event.url_check.status == "down"
      action:
        run_workflow_template:
          name: HR Portal Down
          organization: Default 
