---
- name: Listening for events for Data Guard
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5050
        host: 0.0.0.0
  
  rules:
    - name: Listening for Events from DataGuard Transfer
      condition: event.payload.message contains "RPM is signed"
      action:
        run_job_template:
          name: Demo Job Template
          organization: Default
