---
- name: Listening for events for Data Guard
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5050
        host: 0.0.0.0
  
  rules:
    - name: Listening for Events from DataGuard Transfer
      condition: event.payload.message is search("RPM signature valid") 
      action:
        run_workflow_template:
          name: Everfox Demo
          organization: Default
