---
- name: Check if the nginx config file is modified 
  hosts: edge
  sources:
    - name: file_watch
      ansible.eda.file_watch:
        path: /var/www/html/index.html
        recursive: true

  rules:
    - name: Run the action if the /var/www/html/index.html is modified 
      condition: event.change == "deleted"
      action:
        run_job_template:
          name: fix_cloud_app.yml