---
- name: Check if the nginx config file is modified 
  hosts: localhost
  sources:
    - ansible.eda.file_watch:
        path: /home/ec2-user/papa_johns 
        recursive: true

  rules:
    - name: Trigger job template on file creation 
      condition: event.change == "created"
      action:
        run_job_template:
          name: order_placed.yml