---
- name: Listening for events for Pizza Order System
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5050
        host: 0.0.0.0
  
  rules:
    - name: Order system is Down
      condition: event.payload.issue.entity == "Application" and event.payload.issue.type == "incident" and event.payload.issue.text == "Too many calls with HTTP status code 4XX"
      #condition: event.payload.issue.state == "OPEN" and event.payload.issue.type == "incident" and event.payload.issue.fqdn == "webserver-demo"
      #condition: event.payload.issue.type == "incident" and event.payload.issue.state == "OPEN"
      action:
        run_workflow_template:
          name: Fix Order Processing
          organization: Default
