---
- name: Listening for events for Pizza Order System
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5050
        host: 0.0.0.0
  
  rules:
    - name: Order system is Down
      condition: event.payload.issue.state == "OPEN" and event.payload.customPayloads.custom.alert_message == "pos is down"
      #condition: event.payload.issue.type == "incident" and event.payload.issue.state == "OPEN"
      action:
        run_workflow_template:
          name: Fix Order Processing
          organization: Default
