---
- name: Listening for events for Pizza Order System
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        port: 5050
        host: 54.167.203.238
  
  rules:
    - name: Order system is Down
      condition: Event.payload.ProblemTitle == "Http monitor global outage"
      action:
        run_workflow_template:
          name: Fix Order Processing
          organization: Default  
