---
- name: Listening for events for Pizza Order System
  hosts: localhost
  sources:
    - ansible.eda.url_check:
        verify_ssl: false
        delay: 60
        verify_ssl: false
        urls:
          - http://52.90.75.98
  
  rules:
    - name: Order system is Running
      condition: event.url_check.status == "up"
      action:
        run_job_template:
          name: Pizza Order Placed
          organization: Default 

    - name: Order system is Down
      condition: event.url_check.status == "down"
      action:
        run_workflow_template:
          name: Fix Order Processing
          organization: Default  
