---
- name: Receive Message Events On Webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 127.0.0.1
        port: 5000
        ssl_verify: false

  rules:
    - name: Process message event
      condition: event.payload.message == "Incoming message"
      action:
        run_job_template:
          name: Hello World 
          organization: Default

  
