---
- name: Capture Git Events
  hosts: all
  
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: Run job run_job_template:
      condition: event.payload.message == "Incoming message"
      action:
        run_job_template:
          name: Hello World 
          organization: Default

  