---
- name: Listenfor Events for Web Application
  hosts: all
  sources:
    - ansible.eda.urlcheck:
        urls:
          - http://107.23.128.189

  rules:
    - name: Application is up
      condition: event.url_check.status == "up"
      action:
      run_job_template:
        name:  System Up
        organization: Default

    - name: Application is Down
      condition: event.url_check.status == "down"
      action:
        run_job_template:
          name: Fix Web
          organization: Default 

