---
- name: Close ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Close System Incident
    servicenow.itsm.incident_info:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      query:
        - short_description: LIKE HR Portal is Down
          state: = in_progress
    register: results

  - name: Print out Incident info 
    debug:
      var: results

  - name: Close Incident
    servicenow.itsm.incident:
 #     instance: 
 #       host: "{{ host }}"
 #       username: "{{ username }}"
 #       password: "{{ password }}"
      state: closed
      number: "{{ results.records[0].number }}"
      close_code: "Solved (Permanently)"
      description: Callers reporting HR Portal is not accessible
      close_notes: "Restored previous known good configuration"
