---
- name: Create ServiceNow Incident
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Create HR Portal Incident
    servicenow.itsm.incident:
#      instance: 
#        host: "{{ host }}"
#        username: "{{ username }}"
#        password: "{{ password }}"
      caller: troy.ellis
      short_description: HR Portal is Down
      description: Callers reporting HR Portal is not accessible
      impact: high
      urgency: high
      state: in_progress
