---
- name: Run Disk Check & ServiceNow Incident Python Script in AAP
  hosts: rhel_servers
  gather_facts: false

  vars:
    # Default variables if not provided via AAP Survey or Extra Vars
    incident_urgency: "3"
    incident_impact: "3"

  tasks:
    - name: Run local Python script on target remote nodes
      ansible.builtin.script: files/get_disk_usage.py
      register: script_output

    - name: Parse and display structured JSON output
      ansible.builtin.debug:
        msg: "{{ script_output.stdout | from_json }}"

    - name: Set disk data fact
      ansible.builtin.set_fact:
        disk_payload: "{{ script_output.stdout | from_json }}"

    - name: Execute Python script to create incident
      ansible.builtin.script: files/create_snow.py
      args:
        executable: python3
      environment:
        # Injected automatically by your AAP Custom Credential:
        SN_USERNAME: "{{ lookup('env', 'SN_USERNAME') }}"
        SN_PASSWORD: "{{ lookup('env', 'SN_PASSWORD') }}"
        # Custom dynamic fields passed down to script environment:
        INCIDENT_SUMMARY: "Disk Usage Report: {{ disk_payload.hostname }}"
        INCIDENT_DETAIL: "{{ disk_payload | to_nice_json }}"
        INCIDENT_URGENCY: "{{ incident_urgency }}"
        INCIDENT_IMPACT: "{{ incident_impact }}"
      delegate_to: localhost
      register: script_output
      

    - name: Parse and log ServiceNow response
      ansible.builtin.debug:
        msg: "{{ script_output.stdout | from_json }}"
