---
- name: Site Down
  hosts: webservers
  gather_facts: false
  become: true

  tasks:
  - name: Notiying Site is Down 
    debug:
      msg: "Application is down"

  - name: Restart httpd
    service:
      name: httpd
      state: started
    
  
